project:
  type: website
  output-dir: _site

website:
  title: "Data Stories in Social Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: oda-trends.qmd
        text: The Rise and Fall of Foreign Aid
    right:
      - icon: github
        href: https://github.com/mlss5/data-stories
  page-footer:
    center: "© 2025 Machine Learning for Social Science"

format:
  html:
    theme:
      dark: slate
    css: styles.css
    toc: true
    smooth-scroll: true

execute:
  freeze: auto
  echo: false
  warning: false
